version: "3"

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  redis-transaction:
    image: "redis:latest"
    ports:
      - "6379:6379"

  # SERVICES

  transaction-service:
    image: "newbank/transaction-service"
    restart: always
    environment:
      - POSTGRES_HOST=postgres-transaction:5432
      - POSTGRESQL_DATABASE=database-transaction
    ports:
      - "3000:8080"
    depends_on:
      - postgres-transaction
      - rabbitmq
      - redis-transaction

  cashback-service:
    image: "newbank/cashback-service"
    restart: always
    environment:
      - POSTGRES_HOST=postgres-cashback:5432
      - POSTGRESQL_DATABASE=database-cashback
    ports:
      - "3001:8080"
    depends_on:
      - postgres-cashback

  account-service:
    image: "newbank/account-service"
    restart: always
    environment:
      - POSTGRES_HOST=postgres-account:5432
      - POSTGRESQL_DATABASE=database-account
    ports:
      - "3002:8080"
    depends_on:
      - postgres-account

  affiliated-store-service:
    image: "newbank/affiliated-store-service"
    restart: always
    environment:
      - POSTGRES_HOST=postgres-affiliated-store:5432
      - POSTGRESQL_DATABASE=database-affiliated-store
    ports:
      - "3003:8080"
    depends_on:
      - postgres-affiliated-store

  # DATABASES

  postgres-transaction:
    image: 'bitnami/postgresql:latest'
    container_name: database-transaction
    restart: always
    environment:
      - POSTGRESQL_PASSWORD=postgrespass
      - POSTGRESQL_USER=postgresuser
      - POSTGRESQL_DATABASE=database-transaction
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
    ports:
      - "4000:5432"
    volumes:
      - ./transaction-directory-master:/var/lib/postgresql/data

  postgres-transaction-slave:
    image: 'bitnami/postgresql:latest'
    container_name: database-transaction-slave
    restart: always
    depends_on:
      - postgres-transaction
    environment:
      - POSTGRESQL_USER=postgresuser
      - POSTGRESQL_PASSWORD=postgrespass
      - POSTGRESQL_MASTER_HOST=postgres-transaction
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    ports:
      - "6000:5432"
    volumes:
      - ./transaction-directory-slave:/var/lib/postgresql/data

  postgres-cashback:
    image: 'bitnami/postgresql:latest'
    container_name: database-cashback
    restart: always
    environment:
      - POSTGRESQL_PASSWORD=postgrespass
      - POSTGRESQL_USER=postgresuser
      - POSTGRESQL_DATABASE=database-cashback
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
    ports:
      - "4001:5432"
    volumes:
      - ./cashback-directory-master:/var/lib/postgresql/data

  postgres-cashback-slave:
    image: 'bitnami/postgresql:latest'
    container_name: database-cashback-slave
    restart: always
    depends_on:
      - postgres-cashback
    environment:
      - POSTGRESQL_USER=postgresuser
      - POSTGRESQL_PASSWORD=postgrespass
      - POSTGRESQL_MASTER_HOST=postgres-cashback
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    ports:
      - "6001:5432"
    volumes:
      - ./cashback-directory-slave:/var/lib/postgresql/data

  postgres-account:
    image: postgres:15.2
    container_name: database-account
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_USER=postgresuser
      - POSTGRES_DB=database-account
    ports:
      - "4002:5432"

  postgres-affiliated-store:
    image: postgres:15.2
    container_name: database-affiliated-store
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_USER=postgresuser
      - POSTGRES_DB=database-affiliated-store
    ports:
      - "4003:5432"

    # EXTERNAL SERVICES

  external-bank-mock-service:
    image: "newbank/external-bank-mock-service"
    restart: always
    ports:
      - "5000:8080"

  external-mid-interpreter-mock-service:
    image: "newbank/external-mid-interpreter-mock-service"
    restart: always
    ports:
      - "5001:8080"

  external-mastercard-mock-service:
    image: "newbank/external-mastercard-mock-service"
    restart: always
    ports:
      - "5002:8080"

  external-decathlon-mock-service:
    image: "newbank/external-decathlon-mock-service"
    restart: always
    ports:
      - "5003:8080"

  external-carrefour-mock-service:
    image: "newbank/external-carrefour-mock-service"
    restart: always
    ports:
      - "5004:8080"